version: '3'

volumes:
  postgres-data:
  static:

services:
  postgres:
    image: postgres:latest
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - project.env

  django:
    build:
      context: .
    expose:
      - "8000"
    volumes:
      - static:/home/django/project/static
    env_file:
      - project.env
    depends_on:
      - postgres

  nginx:
    build: nginx
    volumes:
      - static:/home/django/project/static
    depends_on:
      - django

