version: '3'

volumes:
  postgres-data:

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    env_file:
      - project.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  django:
    container_name: django
    build: .
    volumes:
      - .:/srv/project
    env_file:
      - project.env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - postgres

