version: '3'

volumes:
  postgres-data:
  static:
  certbot-conf:
  certbot-www:

services:
  postgres:
    image: postgres:latest
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - project.env

  django:
    build:
      context: .
    expose:
      - "8000"
    volumes:
      - static:/home/django/project/static
    env_file:
      - project.env
    depends_on:
      - postgres

  nginx:
    build: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/home/django/project/static
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    depends_on:
      - django
