version: '3'

volumes:
  postgres-data:

services:
  postgres:
    # TODO: alpine
    image: postgres:latest
    restart: always
    env_file:
      - project.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # TODO: no expose here?

  django:
    build: .
    volumes:
      - .:/srv/project
    env_file:
      - project.env
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
    depends_on:
      - postgres

  nginx:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 1337:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - django

