version: '3'

volumes:
  certbot-conf:
  certbot-www:

services:
  postgres:
    restart: always

  django:
    build:
      target: production
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000 --workers=4
    restart: always
    expose:
      - "8000"

  nginx:
    build: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
      - static:/home/django/project/static
    depends_on:
      - django

  certbot:
    build: certbot
    restart: always
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    depends_on:
      - nginx

