services:
  postgres:
    restart: always

  django:
    build:
      target: production
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000 --workers=4
    restart: always

  nginx:
    restart: always

  certbot:
    build: certbot
    restart: always
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    depends_on:
      - nginx

