services:
  django:
    build:
      target: development
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/django/project

  nginx:
    ports:
      - "80:80"
      - "443:443"

