# Generated by Django 3.1.4 on 2020-12-30 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201230_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='app.attendee'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='app.option'),
        ),
        migrations.AlterField(
            model_name='option',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='app.query'),
        ),
    ]
