# Generated by Django 3.1.4 on 2020-12-31 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201230_2156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AlterModelOptions(
            name='option',
            options={},
        ),
    ]
